name: pr-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # cron job to run after every hour

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install playwright dependencies and Run Tests
        working-directory: src
        run: |
          for dir in $(find "$(pwd)" -type d -name '*_test'); do
            if [ -f "$dir/package.json" ]; then
              echo "Running tests in $dir"
              cd $dir
              # set up playwright
              npm install
              npm ci
              npx playwright install --with-deps
              npx playwright test

              path="$(basename "$(pwd)")"

              echo "Copy artifact from $dir"
              zip $path-playwright-report $path/playwright-report/
              cp $path-playwright-report.zip ../playwright-reports/
            fi
          done

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: src/playwright-reports/
          retention-days: 30
